/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.Timer;
import BUS.SP_BUS;
import DTO.SP_DTO;

/**
 *
 * @author sinht
 */

public class Giaodienchinh extends javax.swing.JFrame {
    public CardLayout card = new CardLayout();
    
    CardLayout cardlayout;
    public Giaodienchinh() {
        initComponents();
       
        cardlayout = (CardLayout) (pnCards.getLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMenu = new javax.swing.JPanel();
        pnacc = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pnlsMenu = new javax.swing.JPanel();
        btnBanhang = new javax.swing.JButton();
        btnNhaphang = new javax.swing.JButton();
        btnSP = new javax.swing.JButton();
        btnLoaiSP = new javax.swing.JButton();
        btnHoadon = new javax.swing.JButton();
        btnPN = new javax.swing.JButton();
        btnKM = new javax.swing.JButton();
        btnNV = new javax.swing.JButton();
        btnKH = new javax.swing.JButton();
        btnNCC = new javax.swing.JButton();
        btnQuyen = new javax.swing.JButton();
        btnTKhoan = new javax.swing.JButton();
        btnTKe = new javax.swing.JButton();
        btnDangxuat = new javax.swing.JButton();
        pnCards = new javax.swing.JPanel();
        pnLogin = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnQuyen = new javax.swing.JPanel();
        pnTop8 = new javax.swing.JPanel();
        jPanel36 = new javax.swing.JPanel();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jPanel37 = new javax.swing.JPanel();
        jPanel38 = new javax.swing.JPanel();
        jComboBox9 = new javax.swing.JComboBox<>();
        jTextField31 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jButton64 = new javax.swing.JButton();
        pnCenter8 = new javax.swing.JPanel();
        jScrollPane13 = new javax.swing.JScrollPane();
        tblSP8 = new javax.swing.JTable();
        pnTKhoan = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(172, 422));

        pnMenu.setBackground(new java.awt.Color(204, 255, 204));
        pnMenu.setPreferredSize(new java.awt.Dimension(170, 45));
        pnMenu.setLayout(new java.awt.BorderLayout());

        pnacc.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 204));
        jLabel1.setText("Quản lí bán bánh");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cake-icon.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Lê Sinh Thái ");

        javax.swing.GroupLayout pnaccLayout = new javax.swing.GroupLayout(pnacc);
        pnacc.setLayout(pnaccLayout);
        pnaccLayout.setHorizontalGroup(
            pnaccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnaccLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pnaccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnaccLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnaccLayout.setVerticalGroup(
            pnaccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnaccLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pnMenu.add(pnacc, java.awt.BorderLayout.PAGE_START);

        pnlsMenu.setBackground(new java.awt.Color(0, 0, 0));
        pnlsMenu.setLayout(new java.awt.GridLayout(14, 1, 0, 5));

        btnBanhang.setBackground(new java.awt.Color(51, 51, 51));
        btnBanhang.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnBanhang.setForeground(new java.awt.Color(51, 255, 204));
        btnBanhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconbanhang.png"))); // NOI18N
        btnBanhang.setText("Bán hàng");
        btnBanhang.setBorderPainted(false);
        btnBanhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanhangActionPerformed(evt);
            }
        });
        pnlsMenu.add(btnBanhang);

        btnNhaphang.setBackground(new java.awt.Color(51, 51, 51));
        btnNhaphang.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnNhaphang.setForeground(new java.awt.Color(51, 255, 204));
        btnNhaphang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconnhaphang.24.png"))); // NOI18N
        btnNhaphang.setText("Nhập hàng");
        btnNhaphang.setBorderPainted(false);
        btnNhaphang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhaphangActionPerformed(evt);
            }
        });
        pnlsMenu.add(btnNhaphang);

        btnSP.setBackground(new java.awt.Color(51, 51, 51));
        btnSP.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnSP.setForeground(new java.awt.Color(51, 255, 204));
        btnSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconsp.png"))); // NOI18N
        btnSP.setText("Sản Phẩm");
        btnSP.setBorderPainted(false);
        btnSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSPActionPerformed(evt);
            }
        });
        pnlsMenu.add(btnSP);

        btnLoaiSP.setBackground(new java.awt.Color(51, 51, 51));
        btnLoaiSP.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnLoaiSP.setForeground(new java.awt.Color(51, 255, 204));
        btnLoaiSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconloaisp.png"))); // NOI18N
        btnLoaiSP.setText("Loại Sản phẩm");
        btnLoaiSP.setBorderPainted(false);
        btnLoaiSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoaiSPActionPerformed(evt);
            }
        });
        pnlsMenu.add(btnLoaiSP);

        btnHoadon.setBackground(new java.awt.Color(51, 51, 51));
        btnHoadon.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnHoadon.setForeground(new java.awt.Color(51, 255, 204));
        btnHoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bill.png"))); // NOI18N
        btnHoadon.setText("Hóa đơn");
        btnHoadon.setBorderPainted(false);
        btnHoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoadonActionPerformed(evt);
            }
        });
        pnlsMenu.add(btnHoadon);

        btnPN.setBackground(new java.awt.Color(51, 51, 51));
        btnPN.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnPN.setForeground(new java.awt.Color(51, 255, 204));
        btnPN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/enter.png"))); // NOI18N
        btnPN.setText("Phiếu Nhập");
        btnPN.setBorderPainted(false);
        btnPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPNActionPerformed(evt);
            }
        });
        pnlsMenu.add(btnPN);

        btnKM.setBackground(new java.awt.Color(51, 51, 51));
        btnKM.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnKM.setForeground(new java.awt.Color(51, 255, 204));
        btnKM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/promotion.png"))); // NOI18N
        btnKM.setText("Khuyến Mãi");
        btnKM.setBorderPainted(false);
        btnKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKMActionPerformed(evt);
            }
        });
        pnlsMenu.add(btnKM);

        btnNV.setBackground(new java.awt.Color(51, 51, 51));
        btnNV.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnNV.setForeground(new java.awt.Color(51, 255, 204));
        btnNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/grouping.png"))); // NOI18N
        btnNV.setText("Nhân viên");
        btnNV.setBorderPainted(false);
        btnNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNVActionPerformed(evt);
            }
        });
        pnlsMenu.add(btnNV);

        btnKH.setBackground(new java.awt.Color(51, 51, 51));
        btnKH.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnKH.setForeground(new java.awt.Color(51, 255, 204));
        btnKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/client.png"))); // NOI18N
        btnKH.setText("Khách hàng");
        btnKH.setBorderPainted(false);
        btnKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKHActionPerformed(evt);
            }
        });
        pnlsMenu.add(btnKH);

        btnNCC.setBackground(new java.awt.Color(51, 51, 51));
        btnNCC.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnNCC.setForeground(new java.awt.Color(51, 255, 204));
        btnNCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/supplier.png"))); // NOI18N
        btnNCC.setText("Nhà cung cấp");
        btnNCC.setBorderPainted(false);
        btnNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNCCActionPerformed(evt);
            }
        });
        pnlsMenu.add(btnNCC);

        btnQuyen.setBackground(new java.awt.Color(51, 51, 51));
        btnQuyen.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnQuyen.setForeground(new java.awt.Color(51, 255, 204));
        btnQuyen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/open.png"))); // NOI18N
        btnQuyen.setText("Quyền");
        btnQuyen.setBorderPainted(false);
        btnQuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuyenActionPerformed(evt);
            }
        });
        pnlsMenu.add(btnQuyen);

        btnTKhoan.setBackground(new java.awt.Color(51, 51, 51));
        btnTKhoan.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnTKhoan.setForeground(new java.awt.Color(51, 255, 204));
        btnTKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user.png"))); // NOI18N
        btnTKhoan.setText("Tài Khoản");
        btnTKhoan.setBorderPainted(false);
        btnTKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTKhoanActionPerformed(evt);
            }
        });
        pnlsMenu.add(btnTKhoan);

        btnTKe.setBackground(new java.awt.Color(51, 51, 51));
        btnTKe.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnTKe.setForeground(new java.awt.Color(51, 255, 204));
        btnTKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/analytics.png"))); // NOI18N
        btnTKe.setText("Thống kê");
        btnTKe.setBorderPainted(false);
        btnTKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTKeActionPerformed(evt);
            }
        });
        pnlsMenu.add(btnTKe);

        btnDangxuat.setBackground(new java.awt.Color(51, 51, 51));
        btnDangxuat.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnDangxuat.setForeground(new java.awt.Color(51, 255, 204));
        btnDangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit_1.png"))); // NOI18N
        btnDangxuat.setText("Đăng xuất");
        btnDangxuat.setBorderPainted(false);
        btnDangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangxuatActionPerformed(evt);
            }
        });
        pnlsMenu.add(btnDangxuat);

        pnMenu.add(pnlsMenu, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnMenu, java.awt.BorderLayout.LINE_START);

        pnCards.setLayout(new java.awt.CardLayout());

        pnLogin.setBackground(new java.awt.Color(0, 255, 204));
        pnLogin.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Chào mừng bạn đã quay trở lại !!!!!!!!!!");
        jPanel1.add(jLabel3);

        pnLogin.add(jPanel1, java.awt.BorderLayout.CENTER);

        pnCards.add(pnLogin, "CardTrangchu");

        pnQuyen.setLayout(new java.awt.BorderLayout());

        pnTop8.setBackground(new java.awt.Color(204, 255, 255));
        pnTop8.setPreferredSize(new java.awt.Dimension(1361, 150));
        pnTop8.setLayout(new java.awt.BorderLayout());

        jPanel36.setBackground(new java.awt.Color(153, 255, 255));
        jPanel36.setPreferredSize(new java.awt.Dimension(1085, 50));

        jButton59.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add1.png"))); // NOI18N
        jButton59.setText("Thêm ");
        jPanel36.add(jButton59);

        jButton60.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/del.png"))); // NOI18N
        jButton60.setText("Xóa");
        jButton60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton60ActionPerformed(evt);
            }
        });
        jPanel36.add(jButton60);

        jButton61.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sua.png"))); // NOI18N
        jButton61.setText("Sửa");
        jButton61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton61ActionPerformed(evt);
            }
        });
        jPanel36.add(jButton61);

        jButton62.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/xls.png"))); // NOI18N
        jButton62.setText("Xuất Excel");
        jButton62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton62ActionPerformed(evt);
            }
        });
        jPanel36.add(jButton62);

        jButton63.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/excel.png"))); // NOI18N
        jButton63.setText("Nhập Excel ");
        jButton63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton63ActionPerformed(evt);
            }
        });
        jPanel36.add(jButton63);

        pnTop8.add(jPanel36, java.awt.BorderLayout.PAGE_START);

        jPanel37.setBackground(new java.awt.Color(153, 255, 255));
        jPanel37.setPreferredSize(new java.awt.Dimension(1085, 150));

        jPanel38.setBackground(new java.awt.Color(204, 255, 255));
        jPanel38.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jComboBox9.setBackground(new java.awt.Color(204, 255, 255));
        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Bánh ngọt ", "Bánh xe" }));

        jTextField31.setBackground(new java.awt.Color(153, 255, 255));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 51, 102));
        jLabel18.setText("Tìm kiếm");

        javax.swing.GroupLayout jPanel38Layout = new javax.swing.GroupLayout(jPanel38);
        jPanel38.setLayout(jPanel38Layout);
        jPanel38Layout.setHorizontalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel38Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField31, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel38Layout.setVerticalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel38Layout.createSequentialGroup()
                .addGroup(jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel38Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel38Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField31)))
                .addContainerGap())
        );

        jPanel37.add(jPanel38);

        jButton64.setBackground(new java.awt.Color(153, 255, 153));
        jButton64.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refresh.png"))); // NOI18N
        jButton64.setText("Làm mới");
        jButton64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton64ActionPerformed(evt);
            }
        });
        jPanel37.add(jButton64);

        pnTop8.add(jPanel37, java.awt.BorderLayout.CENTER);

        pnQuyen.add(pnTop8, java.awt.BorderLayout.PAGE_START);

        pnCenter8.setBackground(new java.awt.Color(255, 204, 255));
        pnCenter8.setPreferredSize(new java.awt.Dimension(161, 450));

        tblSP8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STT", "Mã Quyền", "Tên Quyền", "Chi tiết Quyền"
            }
        ));
        tblSP8.setShowGrid(true);
        tblSP8.setSurrendersFocusOnKeystroke(true);
        jScrollPane13.setViewportView(tblSP8);

        javax.swing.GroupLayout pnCenter8Layout = new javax.swing.GroupLayout(pnCenter8);
        pnCenter8.setLayout(pnCenter8Layout);
        pnCenter8Layout.setHorizontalGroup(
            pnCenter8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCenter8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane13, javax.swing.GroupLayout.DEFAULT_SIZE, 1349, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnCenter8Layout.setVerticalGroup(
            pnCenter8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCenter8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnQuyen.add(pnCenter8, java.awt.BorderLayout.CENTER);

        pnCards.add(pnQuyen, "CardQuyen");

        javax.swing.GroupLayout pnTKhoanLayout = new javax.swing.GroupLayout(pnTKhoan);
        pnTKhoan.setLayout(pnTKhoanLayout);
        pnTKhoanLayout.setHorizontalGroup(
            pnTKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1361, Short.MAX_VALUE)
        );
        pnTKhoanLayout.setVerticalGroup(
            pnTKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 857, Short.MAX_VALUE)
        );

        pnCards.add(pnTKhoan, "CardTK");

        getContentPane().add(pnCards, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cardlayout.show(pnCards, "CardTrangchu");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBanhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanhangActionPerformed
        // TODO add your handling code here:
        pnCards.add(new pnBanHang(),"CardBanhang");
        cardlayout.show(pnCards, "CardBanhang");

    }//GEN-LAST:event_btnBanhangActionPerformed

    private void btnNhaphangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhaphangActionPerformed
        // TODO add your handling code here:
        pnCards.add(new pnNhaphang(),"CardNhaphang");
        cardlayout.show(pnCards,"CardNhaphang");
    }//GEN-LAST:event_btnNhaphangActionPerformed

    private void btnSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSPActionPerformed
        // TODO add your handling code here:
        pnCards.add(new pnSanPham(),"CardSP");
        cardlayout.show(pnCards, "CardSP");
    }//GEN-LAST:event_btnSPActionPerformed

    private void btnLoaiSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoaiSPActionPerformed
        // TODO add your handling code here:
        pnCards.add(new pnLoaiSP(),"CardLoaiSP");
        cardlayout.show(pnCards, "CardLoaiSP");
    }//GEN-LAST:event_btnLoaiSPActionPerformed

    private void btnPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPNActionPerformed
        // TODO add your handling code here:
        pnCards.add(new pnPhieuNhap(),"CardPhieuNhap");
        cardlayout.show(pnCards, "CardPhieuNhap");
    }//GEN-LAST:event_btnPNActionPerformed

    private void btnKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKMActionPerformed
        // TODO add your handling code here:
        pnCards.add(new pnKM(),"CardKM");
        cardlayout.show(pnCards, "CardKM");
    }//GEN-LAST:event_btnKMActionPerformed

    private void btnNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNVActionPerformed
        // TODO add your handling code here:
        pnCards.add(new pnNhanVien(),"CardNV");
        cardlayout.show(pnCards, "CardNV");
    }//GEN-LAST:event_btnNVActionPerformed

    private void btnKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKHActionPerformed
        // TODO add your handling code here:
        pnCards.add(new pnKH(),"CardKH");
        cardlayout.show(pnCards, "CardKH");
    }//GEN-LAST:event_btnKHActionPerformed

    private void btnNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNCCActionPerformed
        // TODO add your handling code here:
        pnCards.add(new pnNCC(),"CardNCC");
        cardlayout.show(pnCards, "CardNCC");
    }//GEN-LAST:event_btnNCCActionPerformed

    private void btnQuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuyenActionPerformed
        // TODO add your handling code here:
        cardlayout.show(pnCards, "CardQuyen");
    }//GEN-LAST:event_btnQuyenActionPerformed

    private void btnTKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKeActionPerformed
        // TODO add your handling code here:
        pnCards.add(new pnTKe(),"CardTKe");
        cardlayout.show(pnCards, "CardTKe");
    }//GEN-LAST:event_btnTKeActionPerformed

    private void txtNgayNhapActionPerformed(java.awt.event.ActionEvent evt) {
        // Create a Date object for the current date and time
    }
    private void btnHoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoadonActionPerformed
        // TODO add your handling code here:
        pnCards.add(new pnHoaDon(),"CardHoadon");
        cardlayout.show(pnCards, "CardHoadon");
    }//GEN-LAST:event_btnHoadonActionPerformed

    private void btnDangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangxuatActionPerformed
        // TODO add your handling code here:
         dispose();
        // Mở form login
        Login lg = new Login();
        lg.setVisible(true);
        lg.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnDangxuatActionPerformed

    private void jButton60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton60ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton60ActionPerformed

    private void jButton61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton61ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton61ActionPerformed

    private void jButton62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton62ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton62ActionPerformed

    private void jButton63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton63ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton63ActionPerformed

    private void jButton64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton64ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton64ActionPerformed

    private void btnTKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKhoanActionPerformed
        // TODO add your handling code here:
        pnCards.add(new pnTK(),"CardTK");
        cardlayout.show(pnCards, "CardTK");
    }//GEN-LAST:event_btnTKhoanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Giaodienchinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Giaodienchinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Giaodienchinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Giaodienchinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Giaodienchinh().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBanhang;
    private javax.swing.JButton btnDangxuat;
    private javax.swing.JButton btnHoadon;
    private javax.swing.JButton btnKH;
    private javax.swing.JButton btnKM;
    private javax.swing.JButton btnLoaiSP;
    private javax.swing.JButton btnNCC;
    private javax.swing.JButton btnNV;
    private javax.swing.JButton btnNhaphang;
    private javax.swing.JButton btnPN;
    private javax.swing.JButton btnQuyen;
    private javax.swing.JButton btnSP;
    private javax.swing.JButton btnTKe;
    private javax.swing.JButton btnTKhoan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JPanel pnCards;
    private javax.swing.JPanel pnCenter8;
    private javax.swing.JPanel pnLogin;
    private javax.swing.JPanel pnMenu;
    private javax.swing.JPanel pnQuyen;
    private javax.swing.JPanel pnTKhoan;
    private javax.swing.JPanel pnTop8;
    private javax.swing.JPanel pnacc;
    private javax.swing.JPanel pnlsMenu;
    private javax.swing.JTable tblSP8;
    // End of variables declaration//GEN-END:variables
}
